services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend-rural
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"